aljazceru/awesome-nostr

README.md
fix my name removing the two "ff"s (not sure this was intentional), remove some old or broken things, add a couple of new ones, rename nostr-chat to loquaz and a typo.
=> bundle of changes

README.md
=> add Jester - Chess over nostr

README.md
Hi, adding Rust library for writing bot I'm working on.
=> Add nostr-bot

README.md
- Updated the link to overview and FAQ
- Added ArcadeCity and Anigma to the list of clients
=> update readme to include ArcadeCity and anigma

README.md
Second exchange is an experimental social media service that lets anyone, anywhere in the world to create content. Second Exchange uses peer-to-peer technology to operate with no central authority, Second Exchange Core is the name of open source software which enables the use of this service.
Create a blog post/content or collections that is stored on client side only and is realyed using nostr.
Follow people and content
Group content
Feature in future like adding tips, votes, and more in pipeline
=> Please add Second.Exchange in the List 

README.md
- fixed broken link
- replace duplicate entry,  combined the 2 entries into 1
=> 2 fixes reagarding nashboard

README.md
=> add nostr.ch - another web client

README.md
This is a shameless plug of my own tool. 
Check it out at https://github.com/8go/nostr-commander-rs before merging PR.  While there, if you like it, give it a :star:
=> added nostr-commander

README.md
I've got a python relay in development, which seems to work well so far.
=> Add new python relay

README.md
I just published 2 TypeScript libraries to make it easier to develop Nostr frontends! Would love to have them featured on this awesome list!
=> Add nostrgg/client and nostrgg/react to list

README.md
I wasn't sure if an entire new section should be added for these or not, so I added it onto the end of the tools section for now.
=> add nostrplebs NIP-05 ID registration service

README.md
Try it out - https://makers.bolt.fun/feed
=> Add bolt.fun to clients list

README.md
Added nostr-deno in libraries.
=> Added nostr-deno in libraries.

README.md
Built [nostr.how](https://nostr.how) as an introduction to nostr and onboarding guide. Will be updating with more content over the coming days.
=> Add nostr.how to readme

README.md
I'm not sure if this is the best way to suggest including the service in this document. Thanks in advance for the review.
=> add plebs.place NIP-05 ID registration service (portuguese)

README.md
..for tools not currently usable or not working right now, or deprecated.
=> added section deprecated

README.md
A key manager for Lightning and nostr.
repo: https://github.com/lnpass/lnpass-web
website: https://lnpass.github.io
=> add lnpass

README.md
=> added new guide

README.md
Adds a new react component that leverages nostr.
=> Add nostr-chat-widget-react

README.md
Added a new astral nostr web client instance
=> New web client entry

README.md
MeShell is a web, iOS and Android blog type client destined to publish articles and researches for independent journalists.
=> Added an upcoming client, MeShell

README.md
Adds nostr.industries registration service to Tools section.
The rest are prettier changes 🤷
=> add nostr.industries registration service

README.md
Also noticed that [UseNostr](https://usenostr.org/) - is no longer working... Not sure if we want to remove it now or wait for some time.
=> Adding a new guide resource under protocol section.

README.md
nostr blog example: 
- https://flycat-web.vercel.app/article/45c41f21e1cf715fa6d9ca20b8e002a574db7bb49e96ee89834c66dac5446b7a/45832
=> Add Flycat web client

README.md
added discord server to communities
=> added discord community server

README.md
=> add strfry relay

README.md
Sorry if it's in the wrong location, was contemplating between clients or libraries.
=> Add new widget (Disgus)

README.md
@Cameri and I started a Nostr telegram channel to assist Spanish speaking community
spread the word
=> add spanish telegram group

README.md
=> Update Hamstr entry

README.md
Let's add NostrID to the list, available here : https://github.com/erdaltoprak/nostrid
=> Add NostrID iOS Client

README.md
Proposal to add it to "Bridges and Gateways" section, its a fork as continuation of the original rsslay by fiatjaf, includes several performance improvements, UX redesign, facilities to deploy, and continuous improvements
=> add rsslay.nostr.moe

README.md
Add nostromat client to the list. Source code here: https://github.com/ekimber/nostromat
=> Add nostromat client

README.md
Adding [nostrview.com](https://nostrview.com)
=> Add nostrview.com

README.md
- [nip06-web](https://github.com/jaonoctus/nip06-web)
- [nip06-cli](https://github.com/jaonoctus/nip06-cli)
=> Add nip06 tools

README.md
https://github.com/chawyehsu/nostr-vanity-address-generator
=> Add tool nostr-vanity-address-generator

README.md
Thank you for maintaining this list!
=> Adding Astro to list of relays

README.md
Thanks for maintaining this list 🙏
=> Add Nex relay

README.md
Thank you for maintaining this list ❤️
=> Add akiomik/nostrends

README.md
I recently wrote a short article about tinkering with the Nostr protocol without installing any client. I.e. how to generate keys, read/write events. I created it as I was looking for such a thing myself and could not find it - hopefully, others find it useful as well.
=> Add link "tinkering with nostr without any client"

README.md
Thanks for this repository - hoping to add Nostr.ly / easyNostr as NIP-05 ID provider
=> Adding Nostr.ly / easyNostr NIP-05 provider

README.md
https://soapbox.pub/blog/mostr-fediverse-nostr-bridge/
=> Add Mostr bridge

README.md
The project is now named Tamga https://github.com/erdaltoprak/tamga/tree/main
=> [FIX] renaming nostrID to Tamga

README.md
Adding a link to a directory of twitter users accounts and their NOSTR addresses
=> added a nostr address book

README.md
I released the Flamingo browser extension for Nostr a few weeks back and would love to have it included in the list 👍
https://www.getflamingo.org
=> Add Flamingo browser extension to list

README.md
A simple tool to generate nostr keypair
=> new: A simple tool to generate nostr keypair

README.md
Add 'Written' a long-form content client.
=> Add 'Written' a long-form content client.

README.md
some links and data were outdated.
=> some updates

README.md
NostrFlu: <https://heguro.github.io/nostr-following-list-util/>
=> Add NostrFlu

README.md
Updates nostr.industries NIP-05 service entry.
Sneaks in some prettier formatting 😅
=> chore: update nostr.industries, add repo link

README.md
An open source web app built with Next.js 13 and TypeScript. Stack: React, Next, TypeScript, Tailwind CSS. Live Instance: www.Nostribe.com
=> add Nostribe.com web app nostr client

README.md
Listr - A Nostr Web Client for Making Lists
=> add Listr a web client for making lists

README.md
Added `monstr` -  python code for working with nostr and updated `nostrpy` whichi is no longer being developed
=> README update: added relay

README.md
This highlight a new developer-experience Dart library for Nostr.
=> Addid dart_nostr library to libraries section

README.md
https://github.com/sepehr-safari/nostr-hooks
React hooks for developing Nostr clients. It's simple and intelligent.
=> add nostr-hooks library

README.md
Add onlyzaps.club open-source NIP-05 service
=> Add NIP-05 service

README.md
this adds Pollstr to README.md
Pollstr is a basic web client for nostr with the focus on polls.
=> add Pollstr to README.md

README.md
Both relay and library are in the same github mono repo.
=> List Nostra Relay and Library

README.md
Pinstr is a decentralized and open-source social network for curating and sharing your interests with the world.
=> add pinstr.app

README.md
We started this community not long ago because there are no other communities like it.
We welcome new members to join existing discussions or start a new one about usage/content on nostr.
We are builders on nostr, so we think we can manage this community.
=> Add an eastern europe community in telegram group for nostr

README.md
=> doc: added signum xt wallet as extension

README.md
Simplify PoW Pub description, add link to web demo
=> Add PowPub demo link

README.md
Also: added another nostr icon repo for visibility.
=> Updated Nostore links now that it's an approved extension.

.vscode/settings.json, README.md
[highlighter](https://highlighter.com/)
[nostriChat](https://nostri.chat/)
[zaplife](https://zaplife.lol/)
[nostrtool](https://nostrtool.com/)
=> added some usefull and fun stuff

README.md
Move listr.lol from deprecated section to clients section as it is still in active development.
=> move listr.lol from deprecated to clients

README.md
=> added habla.news

README.md
Add advanced-nostr-search tool to tools section.
=> Add advanced-nostr-search tool

README.md
I noticed that yakihonne.com was using the stars image from another project. This fixes that.
=> removing incorrect stars link for yakihonne.com

README.md
=> Add atomstr RSS/Atom gateway

README.md
=> add nostr.kiwi

README.md
Adding Nostr-Check.com as free NIP05 service
=> Adding Nostr-Check.com

README.md
=> added 'Nostr NIP-36 Image Redirector'

README.md
=> Add QNostr link

README.md
I hope this excellent project can be added, thanks.
=> Add nostr-crdt

README.md
Added Nostpy relay project to list of relay implementations
=> Add Nostpy relayproject

README.md
WIP typescript library with toys to make it easier getting started
=> add nostr-ts

README.md
Make a small modification, thank you!
=> update the description of nostr-relay-nestjs

README.md
NIP-15 is a protocol for decentralized marketplaces built on top of Nostr. NIP-15 clients are very different from normal "social network"-style clients, hence I added a new section!
=> Add Nostr Marketplace (NIP-15) clients

README.md
A full-featured linktree alternative on Nostr with bonus features.
=> Adding Favvy.com to the list

README.md
Granary has added nostr support and i think it's a useful tool so i'm adding it to the list.
=> adding granary as nostr tool

README.md
See the [repository](https://github.com/sepehr-safari/listr).
=> Move Listr to deprecated section

README.md
* Consistency in naming
* Add NL community
* Remove broken .hk link
* Ordering
=> Reformat community part

README.md
Add siamstr.com to the NIP-05 identity services list
=> Add siamstr.com to the NIP-05 identity services list

README.md
Add Primal mobile clients and fixed some capitalisation
=> Add Primal mobile clients

README.md
Following the redirect that's at the old link
=> Update link to nostr army knife

README.md
Add a section with known NWC-enabled clients and apps.
=> Add NWC section

README.md
Clarified Alby description and added more entries.
=> Add more NWC clients and endpoints

README.md
Fixed spelling mistake "AKA Profile" to "AKA Profiles"
Added new nostr-access-control library to Libraries
Added demo app of nostr-access-control to Tools
=> added nostr access control library and demo app

README.md
Add nosdump and nostr-fetch tools created by @jiftechnify.
=> Add nosdump and nostr-fetch tools

README.md
Please tell me if category is wrong.
=> Add nostter, Nostr action, nostr.json generator and Nostr playground

README.md
=> add noStrudel

README.md
A small Logseq plugin to connect with Nostr https://github.com/KoalaSat/logseq-nostr-sync
=> Add logseq-nostr-sync

README.md
Based on https://github.com/nostr-protocol/nips/blob/master/07.md.
=> Add some NIP-07 implementations

README.md
Adding Postr For Nostr to Clients
=> Adding Postr For Nostr to Clients

README.md
Add two of my projects:
- https://github.com/Yonle/bostr
- https://github.com/Yonle/undelete-my-nostr
=> Add bostr & undelete-my-nostr

README.md
Add [nostr-filter-relay](https://github.com/atrifat/nostr-filter-relay) in relays part.
=> Add nostr-filter-relay

README.md
Added full inside nostr DM (NIP-04) NIP-05 service. No account, no KYC.
=> Added paid NIP-05 service Nostrich House to README.md

README.md
=> Vinaylalco patch 2

README.md
I have renamed this project, and this is the updated repo/name.
Prev pull request: https://github.com/aljazceru/awesome-nostr/pull/237
=> change ourchan.org to get-tao.app

README.md
This PR updates nostr-filter-relay description to match latest repository description.
Thank you.
=> Update nostr-filter-relay description

README.md
Beagle chat is a web3 instant messaging application for IOS. 
Nostr is integrated to show newly registered new and for user to share  moments by posts of text, image and videos.
=> Submit Beagle Chat as a nostr IOS client

README.md
Hey formstr is a google forms alternative on nostr: https://formstr.app , I'm the dev on it, would love to answer any questions you might have.
=> Add Formstr Client

README.md
show the number of stars and modified a little about the description of the project.
=> Add github stars number of Beagle

README.md
Add nuxstr as a reference in the clients list.
https://github.com/sebastix/nuxstr
=> add Nuxstr as a reference

README.md
1. Remove Denostr "support by ByteTrade and Revo"
2. Add Denny to Clients
=> Add Denny to Clients And remove Denostr "support by ByteTrade and Revo"

README.md
added https://playground.nostr.com and its repo.
=> Add Playground

README.md
Important tutorials to software developers who wants implement or be vendors for NOSTR, because teach NIP-01 using general purpose packages
Important to corporative users because use the Jupyter Notebook as environment (too).
=> Add tutorial to newcomers software developers and corporative users

README.md
Removed my abandoned projects, added the new one.
=> Removed abandoned project, added new nostr-badges

README.md
=> Included Nosflare relay implementation and Verified-Nostr.com NIP-05 service

README.md
- added docstr.app
- added osty.dev
- fixed nostr-hooks url
- removed some white-spaces
=> Add Docstr & Osty

README.md
Add https://github.com/dluvian/voyage
=> Add voyage

README.md
=> Move Nozzle to deprecated

README.md
- [plantimals\knob](https://github.com/plantimals/knob): command line tool to post text files to nostr
- [plantimals\nostr-pass](https://github.com/plantimals/nostr-pass): experimenting with nostr priv/pub key pairs for replacing passwords
=> add plantimals

README.md
=> Add Blossom

README.md
I didn't find a section that fits so I created a new p2p section, I hope it's ok for you guys
=> Add mostro repositories

README.md
=> Add NIP-44

README.md
add nostrmo, clrelay and nostr sendbox
=> add nostrmo, clrelay and nostr sendbox

README.md
This adds LUMINA.
It's a Website and PWA App that works on nostr.
=> Add: LUMINA

README.md
Adding https://github.com/Yonle/bostr2 into README & improve existing description
=> Add bostr2 and improve description

README.md
DVMDash is a project that recently launched, see announcement here: https://habla.news/a/naddr1qvzqqqr4gupzpkscaxrqqs8nhaynsahuz6c6jy4wtfhkl2x4zkwrmc4cyvaqmxz3qqxnzdejxv6nyd34xscnjd3sz05q9v
=> added DVMDash project to Readme

README.md
=> Update README.md - Add hivetalk

README.md
We've built this little game on Nostr which uses Zaps to create a provably fair game inspired by SatoshiDice.
=> Add NostrDice

README.md
Added Github repo and live instance for Groups (NIP-29 Group Chat Web Client).
=> Add Groups (NIP-29 Group Chat Web Client)

README.md
A matrix server, hosted by us.  Enough of all this Telegram nonsense :-)
=> Adding chat.nostrdev.com

README.md
Also update nostr-geotags entry
=> add notemine

README.md
=> change get-tao.app to getwired.app

README.md
Added grain relay implementation and badger badge client.
=> Add grain and badger

README.md, data.md
The Nostrpy project hasn't been maintained in 2 years.  
https://github.com/monty888/nostrpy
=> Project no longer maintained

README.md
=> add nostrame in the section NIP-07 Browser extensions

README.md
Nostrdice recently launched a webapp: a simple nostrclient.
=> Add link to nostrdice app

README.md
rsslay has been archived. Also, https://rsslay.nostr.moe/ cannot be opened.
=> Move rsslay to deprecated

README.md
1. Fixed spelling mistake
2. Added NIP-07 Testing App
=> added NIP-07 Signing Extension Tester

README.md
Changed zap.store to rebranded Zapstore.
=> Update README.md zap.store -> Zapstore

README.md
=> Add Jumble

README.md
Updating the link and description for Nos now that it's launched and in the appstore.
=> updating Nos now that it's in the appstore

README.md
There are a few sections where I think Rizful could be added. I picked two, but please let me know if you think they are in the wrong section. Thanks.
=> Add rizful

script.js, styles.css
Touch functionality is much improved as well as better scaling for smaller screens.
=> Mobile UX improvements

index.html, script.js, styles.css
improved the look of he top nav bar and it's organization for mobile users.  Also made the items lists presentation more pleasing with larger icons.  Added logo as favicon for the site.
=> More mobile improvments

README.md, script.js
Some listing were not being displayed.  All appear to be visible now.  Added YEGHRO unFollow tool to the list of Tools.
=> Fine tuning

script.js
as it turns out some more listings were not showing up.  It's fixed now and hopefully all entries should be showing.
=> Some more fine tuning

README.md
Not exactly sure what I am doing... first time ever doing a pull request since I am no programmer and don't really understand the structure of the project, but think it just pulls links from the readme. Hope I didn't bork anything up :)
=> Removed dead link to nostr.guide

README.md
This pull request includes a small but important update to the `README.md` file. The change corrects the GitHub repository URL for the `LUMINA` project, ensuring that it points to the correct repository.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L176-R176): Updated the GitHub repository URL for `LUMINA` to `https://github.com/lumina-rocks/lumina`
=> Update LUMINA in README.md

README.md
Removed 7 lines as they were unresponsive or offline. 
Added 1 free service to the list.
=> Updated NIP-05 providers

README.md
Just adding https://github.com/bitvora/haven by @barrydeen, myself and contributors to the list of relays
=> Update README.md to include HAVEN

README.md
=> Add connect4, Citrine and nostr.cooking

README.md
Make these icons look better in nostr.net.
=> Improve Amethyst and Zapstore links in Most popular section

README.md
I would like to add the client I am currently working on
=> Add Hook Cafe client

script.js, styles.css
- fix google url since it defaults to http not https
- some color suggestions. 
- i would get rid of the dropdown for themes and just use two, dark and light to make it easier to maintain
=> some suggestions

index.html, script.js
- Comment out theme dropdown since the colors don't look so good when selecting the other options
- Fix js to handle the commented out select dropdown
=> Comment out theme select dropdown

README.md
Add Shugur to the list of Nostr relays in README.md
=> Add Shugur relay implementation to Nostr relays list

README.md
I just launched v0.1.0 of my Nostr-client. It would be nice if it was added to this list.
Source code: [https://gitlab.com/intercreate-online/breefly](https://gitlab.com/intercreate-online/breefly)
Thanks in advance!
=> Add Breefly
