aljazceru/awesome-nostr

- README.md
would like to add my astral site and client (https://astral.ninja/ and https://github.com/monlovesmango/astral)
> add astral to Sites and Clients

- README.md
Hello!
[Minds](https://www.minds.com/) is an open source social network, and we're currently working on integrating our site with the Nostr protocol. This PR adds a link to our site, our relay, and the portions of our API that are relevant to Nostr.
Please let me know if you have any issues with what I've added here.
> add links to Minds.com and relevant Nostr infastructure

- README.md
removed defunct branle.orange.surf
added NostrPostrRelay
video links via youtube search
removed lots of redundant mentions of "nostr"
moved stuff from "clients" to "tools" and "other links"
> rearranged the links

- README.md
[NostrKit](https://github.com/cnixbtc/NostrKit) is a simple client library for interacting with Nostr relays when writing iOS and macOS apps (or anything else that you might do with Swift).
> Add NostrKit (Swift client library)

- README.md
This removes the link to my `nostr-rs` fork, because there are a few other links in the list which are better maintained and support more NIPs.
> Removed link to `nostr-rs` fork

- README.md
Currently under app stores review but I wanted to call dibs on the name because it is important for the app philosophy
> Add nostr-attached OSS ReactNative Expo app project

- README.md
Add a link to a publicly available dataset of Nostr events.  Hopefully this will be helpful to anyone wanting to do analysis on Nostr tools using reproducible data.
> Add link to public Nostr datasets

- README.md
Nostr search feature is moved from realsearch.cc to a dedicated website nostr.band
> Replace realsearch.cc with nostr.band

- README.md
Visit https://www.sovereign-stack.org for more details. The git repo for the project can be found at https://git.sovereign-stack.org/ss/sovereign-stack
> Added Sovereign Stack to Tools section.

- README.md
The name of my [nostr-react](https://github.com/t4t5/nostr-react) library has been updated, and I've deprecated [nostrgg-client](https://github.com/nostrgg/nostrgg-client) in favour of [nostr-tools](https://github.com/nbd-wtf/nostr-tools). Updating the list so that it's up-to-date for new builders! 👍
> Update nostr-react link

- README.md
When that descripttion was drafted it made sense, it no longer does as peers no longer include a qualifier in their description
> Remove qualifier in nostr.watch description

- README.md
Adds https://rubygems.org/gems/nostr / https://github.com/wilsonsilva/nostr to the list. Clients can use it. I'm in the process of adding Relay support as well.
> Add the nostr Ruby gem

- README.md
Replaced the link with the one from medium.com. The reason is that one can see comments there.
> Replace the link for "tinkering with nostr without any client"

- README.md
Hi,
I've just created a library adding some helper functions for Nostr in PHP.
This requests adds that link to the README in the libraries section.
The package itself is used by the Drupal module at https://www.drupal.org/project/nostr_simple_publish/ but haven't added that yet as I have no clear idea where I'd put it (it's not a relay, rather a - very - simple module that sends text messages to the nostr network)
Thanks
> Add PHP library to README

- README.md
Deno based, cloud native nostr implemention support by ByteTrade and Revo
> added denostr to list of relays

- README.md
I have changed domains and the repo name - this PR updates everything with the correct links
> chore: rebrand nostr.industries to zaps.lol

- README.md
Hi, i'd like to submit the [Nostrss](https://github.com/Asone/nostrss)  tool i built to the list. 
Hoping it will fit in the list. 
Please feel free to tell me if there's something missing or tell me why it wouldn't fit here if that was the case. 
Side-note : the repo also provides a list of npubs of feeds already broadcasted through my personal instance. Should that go somewhere in the curation list too ? 
Many thanks ! 
Kind regards, 
Asone
> Add nostrss

- README.md
Meshtastic is an open source, off-grid, decentralized, mesh network built to run on affordable, low-power devices. This tool allows users to send (only) short nostr messages while off-grid on a hike or without Internet access.
> Add link to off-grid messaging solution

- README.md
https://github.com/kaiwolfram/Nozzle is no more.
It got transferred to me a while ago.
> Fix link to Nozzle repository and update description

- README.md
Add nostr-one in libraries
https://github.com/dolu89/nostr-one
Repo Description: The `<nostr-one>` custom element is a reusable web component that provides a simple way to integrate with the Nostr [NIP 98](https://github.com/nostr-protocol/nips/blob/master/98.md) HTTP Auth. It can be used in any web project that supports custom elements.
Awesome-nostr description: A reusable web component that provides a simple way to integrate with the Nostr NIP 98 HTTP Auth.
> Add nostr-one

- README.md
nostr-delete is a microapp to generate and blast out delete events. It's useful and should be included in awesome-nostr.
> adding link to nostr-delete microapp

- README.md
https://lume.nu recently added NWC support.
> Add Lume.nu as NWC client

- README.md
Add [nostro](https://github.com/r3drun3/nostro) under **Tools**.   
`nostro` stands for `nostr osint` and is a tool to facilitate `open source intelligence` operations on the `nostr` ecosystem.
> docs(readme): add nostro tool

- README.md
Adding OneKey to the NIP-07 List.
I'm excited to share with everyone that OneKey now fully supports NIP07.
[OneKey](https://onekey.so/) is a completely open-source wallet. Here is our PR and documentation for the work we've done for Nostr.
PR: https://github.com/OneKeyHQ/app-monorepo/pull/3864
Document: https://developer.onekey.so/connect-to-software/webapp-connect-onekey/nostr/guide
> Add OneKey to NIP-07 Supported browser extensions list

- README.md
Inbox was based on an old version of the spec, and so isn't compatible. I recently ported Coracle's DMs to a separate standalone application.
> remove inbox, add coracle dms

- README.md
Flamingo's last commit is about a year ago and even so it doesn't support the whole spec, so it often breaks, unfortunately.
It's easily the best looking one though. :)
> Remove Flamingo Extension

- README.md
Added links for:
* [nostpy-cli](https://github.com/UTXOnly/nostpy-cli)
* A Python CLI client/tool for relay development
* [zap_server](https://github.com/UTXOnly/zap_server)
* LNURL server for accepting Zaps to tor hosted node, generates kind 9735 zap receipt event upon successful payment
> Add zap_server and nostpy-cli

- README.md
added Github repo and live instance address for NIP-29 Group Chat Relay.
> Add NIP-29 Group Chat Relay

- README.md
IMO, there are appropriate the Clients section rather than the Relays section.
> Move alphaama and mapstr to Clients section

- README.md
- data.md
Hi,
I was looking for a nostr application to test and noticed that Bija is no longer maintained.
https://github.com/BrightonBTC/bija
> Removing Bija as is no longer maintained

- README.md
- data.md
See below:
https://github.com/nodetec/notestack/issues/144#issuecomment-2311300663
> Domain was changed from blogstack.io to https://notestack.com/

- README.md
- Deprecated MutinyWallet's Blastr and replaced with Nosflare's Send It.
- Added Anonostr client
- Added NostrMedia.com NIP-96 uploader
- Changed domain for verified-nostr.com
> Updated listings

- README.md
Adds repo for metadata updater tool which scans all known online nostr relays for stale kind 0 metadata notes, rebroadcasts latest verified note to relays with stale metadata
> Add metadata_updater tool

- README.md
Thats a bridge I did because I wanted a client like RSS to view nostr, so it was easier to make a bridge then to create a new client
> Added nostr-to-rss, a bridge enabling RSS clients to read Nostr contents

- README.md
I'm creating a relay implementation and want to build in the open.
> Added tandem to list of relay implementations

- README.md
Added two tool links
publsp: a cli tool for LSPs to publish & manage liquidity ads on nostr
liquiditystr: a browser client to pull liquidity ad events by LSPs and coordinate liquidity purchases
> Update tool list on README.md

- README.md
Hi Aljaz. I hope you are well.
I would like to submit for your approval Nostr projects I have made or used extensively together with other community members for your Awesome Nostr repo.
- SW2, I contributed to Bitvora's relay and use this daily. It is unique in its simple ability to control read and write whitelists with NIP-42 authentication for small communities and other private uses. I personally daily drive this with Jumble.social and find it to be very useful.
- Shosho, I have built this app upon Kieran's strong foundations with Zap Stream. Allows users to go live IRL from their phone camera and chat with users live on the stream. Works on Android, iOS and web with support Zap.Stream servers and any other generic RTMP ingest server, so users can bring their own. Streams are 30311 …
> Add Shosho, Nostrobots, and SW2
